# This is a basic workflow to help you get started with Actions

name: unittest-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ] # Noone should push to deployment directly.
  pull_request:
    branches: [ master, deployment ]

jobs:
  unittest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check versions of everything
        run: |
          docker --version;
          docker-compose --version;
          tar --version;
          gzip --version
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      - name: Do docker-compose build 
        run: docker-compose -f docker-compose-testing.yml build
    
      - name: Do docker-compose up
        run: docker-compose -f docker-compose-testing.yml up --abort-on-container-exit
   
