# This is a basic workflow to help you get started with Actions

name: unittest-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ] # Noone should push to deployment directly.
  pull_request:
    branches: [ master, deployment ]

jobs:
  unittest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Do docker-compose build 
      run: docker-compose build -f docker-compose-testing.yml
    
    - name: Do docker-compose up 
      run: docker-compose up -f docker-compose-testing.yml --abort-on-container-exit
   
